site_url: https://pycottas.readthedocs.io

site_name: pycottas

repo_url: https://github.com/arenas-guerrero-julian/pycottas
edit_uri: ""

copyright: Copyright &copy; 2023 Julián Arenas-Guerrero | Universidad Politécnica de Madrid

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  #logo: assets/logo.png
  #favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font: false
  features:
      navigation.instant
      navigation.tracking
      navigation.sections
      navigation.expand
      navigation.tabs
      navigation.indexes
      toc.integrate
      toc.follow
      content.code.copy
      content.code.select
      content.code.annotate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arenas-guerrero-julian/pycottas
      name: pycottas on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pycottas/
      name: pycottas on PyPi
    - icon: fontawesome/solid/paper-plane
      link: mailto:<julian.arenas.guerrero@upm.es>
      name: Contact email
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ArenasGuerreroJ
      name: pycottas announcements on Twitter
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Documentation: documentation.md
